task:
    name: amsp
    timeout_in: 240m
    container:
      image: ubuntu:latest
      cpu: 8  
      memory: 32G 
    run_script: # To sync source
      - DEBIAN_FRONTEND=noninteractive
      - TZ=Asia/Jakarta
      - apt update && apt upgrade -y
      - apt-get install git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 libncurses5-dev lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig -y
      - mkdir ~/bin
      - PATH=~/bin:$PATH
      - curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
      - chmod a+x ~/bin/repo
      - git config --global user.name Your Name
      - git config --global user.email you@example.com
      - repo init --depth=1 -u git://github.com/DotOS/manifest.git -b dot11
      - repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags --optimized-fetch --prune
      - cd project
      - git clone https://github.com/Orangeskai/android_device_realme_RMX2001 -b DotOs --depth=1 device/realme/RMX2001
      - git clone https://github.com/Orangeskai/android_kernel_realme_RMX2001 -b DotOs --depth=1 kernel/realme/RMX2001
      - git clone https://github.com/Orangeskai/proprietary_vendor_realme -b Dotos --depth=1 vendor/realme
      - git clone https://github.com/Orangeskai/android_device_realme_mt6785-common -b lineage-18.1 --depth=1 device/realme/mt6785-common
      - source build/envsetup.sh
      - lunch dot_RMX2001-userdebug
      - make bacon -j$(nproc --all)
      - up out/target/product/RMX2001/*.zip
      - up(){curl --upload-file $1 https://transfer.sh/$(basename $1); echo}
